#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR) -L../../../usr/local/lib
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/rel

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR) -L../../../usr/local/lib
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = relais

OBJ_DEBUG = $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/src/dictionary.o $(OBJDIR_DEBUG)/src/firmata.o $(OBJDIR_DEBUG)/src/iniparser.o $(OBJDIR_DEBUG)/src/serial.o $(OBJDIR_DEBUG)/src/servo.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/src/dictionary.o $(OBJDIR_RELEASE)/src/firmata.o $(OBJDIR_RELEASE)/src/iniparser.o $(OBJDIR_RELEASE)/src/serial.o $(OBJDIR_RELEASE)/src/servo.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/main.o: main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.c -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/src/dictionary.o: src/dictionary.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/dictionary.c -o $(OBJDIR_DEBUG)/src/dictionary.o

$(OBJDIR_DEBUG)/src/firmata.o: src/firmata.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/firmata.c -o $(OBJDIR_DEBUG)/src/firmata.o

$(OBJDIR_DEBUG)/src/iniparser.o: src/iniparser.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/iniparser.c -o $(OBJDIR_DEBUG)/src/iniparser.o

$(OBJDIR_DEBUG)/src/serial.o: src/serial.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/serial.c -o $(OBJDIR_DEBUG)/src/serial.o

$(OBJDIR_DEBUG)/src/servo.o: src/servo.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/servo.c -o $(OBJDIR_DEBUG)/src/servo.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.c -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/src/dictionary.o: src/dictionary.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/dictionary.c -o $(OBJDIR_RELEASE)/src/dictionary.o

$(OBJDIR_RELEASE)/src/firmata.o: src/firmata.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/firmata.c -o $(OBJDIR_RELEASE)/src/firmata.o

$(OBJDIR_RELEASE)/src/iniparser.o: src/iniparser.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/iniparser.c -o $(OBJDIR_RELEASE)/src/iniparser.o

$(OBJDIR_RELEASE)/src/serial.o: src/serial.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/serial.c -o $(OBJDIR_RELEASE)/src/serial.o

$(OBJDIR_RELEASE)/src/servo.o: src/servo.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/servo.c -o $(OBJDIR_RELEASE)/src/servo.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/src

install:
	cp relais /usr/bin

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

